export const enum Actions{
    SET_CURRENT_SONG = 'SET_CURRENT_SONG',
    TOGGLE_RANDOM = 'TOGGLE_RANDOM',
    TOGGLE_REPEAT = 'TOGGLE_OPTIONS',
    TOGGLE_PLAYING = 'TOGGLE_PLAYING',
    SET_SONGS_ARRAY = 'SET_SONGS_ARRAY'
}